#zookeeper:
#  image: wurstmeister/zookeeper
#  ports:
#    - "32772:2181"
#kafka:
#  image: wurstmeister/kafka:latest
#  ports:
#    - "9092"
#  links:
#    - zookeeper:zk
#  environment:
#    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#    KAFKA_CREATE_TOPICS: "model:1:1,route:1:1,track:1:1,identify:1:1"
#    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#kafka-manager:
#  image: sheepkiller/kafka-manager
#  ports:
#    - "9000:9000"
#  links:
#    - zookeeper:zk
#  environment:
#    ZK_HOSTS: zk:2181

nginx:
    image: yetta/nginx
    links:
        - graphql0:graphql0
        - graphql1:graphql1
        - graphql2:graphql2
        - admin0:admin0
    ports:
        - "80:80"
graphql0:
    image: yetta/graphql-server
    volumes:
      - ~/env/graphql-server/env.dev.list:/app/env.dev.list
      - ~/env/graphql-server/firebaseDev.json:/app/firebaseDev.json
graphql1:
    image: yetta/graphql-server
    volumes:
      - ~/env/graphql-server/env.dev.list:/app/env.dev.list
      - ~/env/graphql-server/firebaseDev.json:/app/firebaseDev.json
graphql2:
    image: yetta/graphql-server
    volumes:
      - ~/env/graphql-server/env.dev.list:/app/env.dev.list
      - ~/env/graphql-server/firebaseDev.json:/app/firebaseDev.json

admin0:
    image: yetta/admin-console
    volumes:
        - ~/env/admin-console/development.js:/app/server/config/environment/development.js
        - ~/env/admin-console/production.js:/app/server/config/environment/production.js
